
[functions.feedback-emailer]
enabled = true
verify_jwt = true
import_map = "./functions/feedback-emailer/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/feedback-emailer/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/feedback-emailer/*.html" ]

[functions.certificate-generator]
enabled = true
verify_jwt = true
import_map = "./functions/certificate-generator/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/certificate-generator/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/certificate-generator/*.html" ]
